# Generated by Django 4.2.2 on 2023-10-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=12)),
                ('ownername', models.CharField(max_length=20)),
                ('rollno', models.CharField(max_length=5)),
                ('owneremail', models.EmailField(max_length=15)),
                ('accesscode', models.CharField(max_length=7)),
            ],
        ),
    ]
